# Generated by Django 4.2.1 on 2024-03-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='publish',
            field=models.CharField(choices=[('0', 'no'), ('1', 'yes')], default='0', max_length=1),
        ),
    ]
