# Generated by Django 4.2.1 on 2024-03-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('data_base_type', models.CharField(blank=True, max_length=255, null=True)),
                ('data_base', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
